"""Recovery harness (plan §9 phase 3): generate reads from a known spec, run one evidence mode's source and
fitters on them, and compare the fitted spec with the truth.

A mode is a function (templates, reads, mates, truth) -> fitted spec; each evidence mode plugs one in as it
lands. `cigar_mode` refits from the generator's own CIGARs, the upper bound the other modes are judged by.

`compare` computes expectations under both specs on held-out generated tuples (not sampled counts, so the
curves carry no sampling noise), plus Q-track statistics from reads generated by each spec:

- errors: op-probability TV and KL, marginal rate, rate by read position and by reported Q;
- qualities: per-position Q histogram TV, Q lag-1 autocorrelation, empirical Q = -10 log10 P(error | Q).

`TOLERANCES` are the phase 2 exit criteria. `python -m sequencing_error_model.recovery` runs it at scale.
"""

import argparse
import json
import sys
from collections.abc import Callable, Sequence
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

from sequencing_error_model import spec as spec_io
from sequencing_error_model.fit import error, quality
from sequencing_error_model.fit.quality import Array
from sequencing_error_model.generate import Read, _flank, fragments, generate, insert_sizes, observations
from sequencing_error_model.observations import CountTable
from sequencing_error_model.sources import bam
from sequencing_error_model.spec import Component, ErrorModelSpec

Mode = Callable[[list[str], list[Read], list[int], ErrorModelSpec], ErrorModelSpec]
Draw = Callable[[np.random.Generator, int], tuple[list[str], list[int]]]
TOLERANCES = {"rate": 0.05, "rate_by_q": 0.10, "q_position_tv": 0.05}
_K = len(error.CATEGORIES)


def example_spec() -> ErrorModelSpec:
    """A small Illumina-like truth (binned Q, reads of 30-40 bases) that exercises both heads."""
    errors = np.r_[0, np.ones(_K - 1)]
    lags = np.zeros((1, 5, 4))
    lags[0, :4] = 2.5 * np.eye(4)  # sticky qualities
    q_context = np.zeros((3, 5, 4))
    q_context[1, 2] = [1.5, 0.5, -0.5, -1.5]  # low Q on G
    window = np.zeros((3, 5, _K))
    window[1, :4] = np.outer([2.0, 1.0, 0.0, -1.0], errors)  # more errors at low Q
    window[2, :4] = np.outer([0.7, 0.3, 0.0, -0.3], errors)  # and before a low-Q base
    e_context = np.zeros((3, 5, _K))
    e_context[0, 2, 1:5] = 1.2  # substitutions after G
    runs = np.zeros((5, _K))
    runs[2:, 5:] = 1.5  # indels in runs of 3+
    return ErrorModelSpec(
        (2, 12, 23, 37),
        {"mode": "reference", "sources": ["example"]},
        (
            Component("QualityMarkov(1)", {"bias": np.array([-1.0, 0.0, 0.5, 1.5]), "lags": lags}),
            Component(
                "Position(3)",
                {
                    "knots": np.linspace(0, np.log(40), 3),
                    "start": np.zeros((3, 4)),
                    "end": np.array([[1.5, 0.5, -0.5, -1.5], [0] * 4, [0] * 4]),  # end-of-read decay
                },
            ),
            Component("Mate", {"weights": np.array([[0, 0, 0, 0.5], [0.5, 0, 0, -0.5]])}),
            Component("Context(1,1)", {"weights": q_context}),
        ),
        (
            Component(
                "QualityWindow(1)",
                {"bias": np.array([0, -4.0, -4.0, -4.0, -4.0, -6.5, -6.5, -6.5, -6.5, -6.0]), "window": window},
            ),
            Component("Context(1,1)", {"weights": e_context}),
            Component("Homopolymer", {"weights": runs}, meta={"flank": [2, 2]}),
            Component("Mate", {"weights": np.outer([0, 0.3], errors)}),
        ),
    )


def _tuples(model: ErrorModelSpec, templates: Sequence[str], reads: Sequence[Read], mates: Sequence[int]) -> CountTable:
    """Head E tuples wide enough for both heads' context and Q windows."""
    e, q = _flank(model.error_head), _flank(model.quality_head)
    m = max(model.error_head[0].args[0], model.quality_head[0].args[0])
    return observations(zip(templates, reads, mates, strict=True), (max(e[0], q[0]), max(e[1], q[1])), m)


def cigar_mode(templates: list[str], reads: list[Read], mates: list[int], truth: ErrorModelSpec) -> ErrorModelSpec:
    """Refit both heads (with the truth's tokens) from tuples re-derived from the generator's own CIGARs."""
    return bam.fit(
        _tuples(truth, templates, reads, mates),
        truth.quality_alphabet,
        [c.token for c in truth.error_head],
        [c.token for c in truth.quality_head],
        {"mode": "reference", "sources": ["generator-cigar"]},
    )


@dataclass
class Report:
    scalars: dict[str, float] = field(default_factory=dict)
    curves: dict[str, list[float]] = field(default_factory=dict)

    def failures(self) -> list[str]:
        """Phase 2 exit criteria that this report misses."""
        out = []
        if abs(self.scalars["rate_ratio"] - 1) > TOLERANCES["rate"]:
            out.append(f"marginal error rate ratio {self.scalars['rate_ratio']:.3f}")
        by_q = np.array(self.curves["rate_by_q_fit"]) / np.array(self.curves["rate_by_q_true"])
        if np.nanmax(np.abs(by_q - 1)) > TOLERANCES["rate_by_q"]:
            out.append(f"error rate ratio by reported Q {np.round(by_q, 3).tolist()}")
        if self.scalars["q_position_tv_max"] > TOLERANCES["q_position_tv"]:
            out.append(f"per-position Q TV {self.scalars['q_position_tv_max']:.3f}")
        return out


def _rate(key: Array, values: Array, errors: Array, n: Array) -> list[float]:
    return [float(errors[key == v].sum() / n[key == v].sum()) if (key == v).any() else float("nan") for v in values]


def _q_hist(tracks: Sequence[Array], alphabet: Array, top: int) -> Array:
    h = np.zeros((top, len(alphabet)))
    for track in tracks:
        np.add.at(h, (np.arange(top), np.searchsorted(alphabet, track[:top])), 1)
    return h / h.sum(axis=1, keepdims=True)


def _lag1(tracks: Sequence[Array]) -> float:
    x = np.concatenate([t[:-1] for t in tracks])
    y = np.concatenate([t[1:] for t in tracks])
    return float(np.corrcoef(x, y)[0, 1])


def compare(
    truth: ErrorModelSpec,
    fitted: ErrorModelSpec,
    templates: Sequence[str],
    mates: Sequence[int],
    rng: np.random.Generator,
    q_reads: int = 20000,
    substitutions_only: bool = False,
) -> Report:
    """Metrics of `fitted` against `truth` on reads generated from `templates`; Q-track statistics use at least
    `q_reads` sampled tracks per spec. `substitutions_only` compares both heads E conditional on no indel, the
    support of `pe-overlap`."""
    alphabet = np.asarray(truth.quality_alphabet)
    true_reads = generate(truth, templates, mates, rng)
    table = _tuples(truth, templates, true_reads, mates)
    n = np.array(list(table.counts.values()), float)
    p_true, p_fit = (error.probabilities(s.error_head, truth.quality_alphabet, table) for s in (truth, fitted))
    if substitutions_only:
        p_true, p_fit = (
            np.pad(p[:, :5] / p[:, :5].sum(axis=1, keepdims=True), ((0, 0), (0, _K - 5))) for p in (p_true, p_fit)
        )
    with np.errstate(divide="ignore", invalid="ignore"):
        kl = np.where(p_true > 0, p_true * np.log(p_true / p_fit), 0.0).sum(axis=1)
    e_true, e_fit = n * (1 - p_true[:, 0]), n * (1 - p_fit[:, 0])
    q, pos = (np.array([k[table.fields.index(f)] for k in table.counts]) for f in ("q", "pos_start"))
    positions = np.unique(pos)

    # Q-track statistics compare two samples, so draw enough tracks (tiling the templates) that sampling
    # noise stays well under the TV tolerance.
    reps = -(-q_reads // len(templates))
    tiled, tiled_mates = list(templates) * reps, list(mates) * reps
    q_true, q_fit = (
        quality.sample(s.quality_head, truth.quality_alphabet, tiled, tiled_mates, rng) for s in (truth, fitted)
    )
    top = min(len(t) for t in templates)
    tv = 0.5 * np.abs(_q_hist(q_true, alphabet, top) - _q_hist(q_fit, alphabet, top)).sum(axis=1)
    rate_q = {name: _rate(q, alphabet, e, n) for name, e in (("true", e_true), ("fit", e_fit))}
    return Report(
        scalars={
            "op_tv": float(n @ (0.5 * np.abs(p_true - p_fit).sum(axis=1)) / n.sum()),
            "op_kl": float(n @ kl / n.sum()),
            "rate_true": float(e_true.sum() / n.sum()),
            "rate_fit": float(e_fit.sum() / n.sum()),
            "rate_ratio": float(e_fit.sum() / e_true.sum()),
            "q_position_tv_max": float(tv.max()),
            "q_lag1_true": _lag1(q_true),
            "q_lag1_fit": _lag1(q_fit),
        },
        curves={
            "reported_q": alphabet.tolist(),
            "rate_by_q_true": rate_q["true"],
            "rate_by_q_fit": rate_q["fit"],
            "empirical_q_true": (-10 * np.log10(rate_q["true"])).tolist(),
            "empirical_q_fit": (-10 * np.log10(rate_q["fit"])).tolist(),
            "position": positions.tolist(),
            "rate_by_position_true": _rate(pos, positions, e_true, n),
            "rate_by_position_fit": _rate(pos, positions, e_fit, n),
            "q_position_tv": tv.tolist(),
        },
    )


def recover(
    truth: ErrorModelSpec,
    n_reads: int,
    seed: int = 0,
    mode: Mode = cigar_mode,
    lengths: tuple[int, int] = (30, 41),
    draw: Draw | None = None,
    substitutions_only: bool = False,
) -> tuple[ErrorModelSpec, Report]:
    """Generate `n_reads` from `truth`, fit with `mode`, and compare on `n_reads // 2` held-out reads.

    `draw(rng, n)` gives n templates and their mates (default: independent random reads of `lengths`)."""
    rng = np.random.default_rng(seed)

    def single(rng: np.random.Generator, n: int) -> tuple[list[str], list[int]]:
        templates = ["".join(rng.choice(list("ACGT"), size=rng.integers(*lengths))) for _ in range(n)]
        return templates, [int(m) for m in rng.integers(1, 3, size=n)]

    draw = draw or single
    templates, mates = draw(rng, n_reads)
    fitted = mode(templates, generate(truth, templates, mates, rng), mates, truth)
    held, held_mates = draw(rng, max(n_reads // 2, 2))
    return fitted, compare(truth, fitted, held, held_mates, rng, substitutions_only=substitutions_only)


def paired_draw(read_length: int, insert_mean: float, insert_sd: float, genome_length: int = 100_000) -> Draw:
    """A `draw` of interleaved mate 1, mate 2 templates from `generate.fragments` on a random genome."""

    def draw(rng: np.random.Generator, n: int) -> tuple[list[str], list[int]]:
        genome = "".join(rng.choice(list("ACGT"), size=genome_length))
        pairs = fragments([("g", genome)], insert_sizes(insert_mean, insert_sd), n // 2, read_length, rng)
        return [t for _, r1, r2 in pairs for t in (r1, r2)], [1, 2] * (n // 2)

    return draw


def main(argv: Sequence[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        prog="python -m sequencing_error_model.recovery", description="Recovery harness: generate, refit, compare."
    )
    p.add_argument("--spec", type=Path, help="truth spec directory (default: the built-in example spec)")
    p.add_argument("--reads", type=int, default=3000)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--output", type=Path, help="write the full report as JSON")
    args = p.parse_args(argv)
    _, report = recover(spec_io.load(args.spec) if args.spec else example_spec(), args.reads, args.seed)
    doc = {"reads": args.reads, "seed": args.seed, "failures": report.failures(), **vars(report)}
    if args.output:
        args.output.write_text(json.dumps(doc, indent=2) + "\n")
    print(json.dumps({"failures": doc["failures"], **report.scalars}, indent=2))
    return 1 if doc["failures"] else 0


if __name__ == "__main__":
    sys.exit(main())
