"""Recovery harness (plan §9 phase 3): generate reads from a known spec, run one evidence mode's source and
fitters on them, and compare the fitted spec with the truth.

A mode is a function (templates, reads, mates, truth) -> fitted spec; each evidence mode plugs one in as it
lands. `cigar_mode` refits from the generator's own CIGARs, the upper bound the other modes are judged by.

`compare` computes expectations under both specs on held-out generated tuples (not sampled counts, so the
curves carry no sampling noise), plus Q-track statistics from reads generated by each spec:

- errors: op-probability TV and KL, marginal rate, rate by read position and by reported Q;
- qualities: per-position Q histogram TV, Q lag-1 autocorrelation, empirical Q = -10 log10 P(error | Q).

`TOLERANCES` are the phase 2 exit criteria. `python -m sequencing_error_model.recovery` runs it at scale.
"""

import argparse
import json
import subprocess
import sys
import tempfile
from collections import Counter
from collections.abc import Callable, Sequence
from dataclasses import dataclass, field, replace
from itertools import groupby
from pathlib import Path
from typing import Any

import numpy as np

from sequencing_error_model import spec as spec_io
from sequencing_error_model.fit import error, indel, quality
from sequencing_error_model.fit.quality import Array
from sequencing_error_model.generate import (
    Read,
    _edits,
    _flank,
    _revcomp,
    fragments,
    generate,
    indel_events,
    insert_sizes,
    observations,
    realign,
)
from sequencing_error_model.observations import CountTable, Key
from sequencing_error_model.sources import bam
from sequencing_error_model.spec import Component, ErrorModelSpec

Mode = Callable[[list[str], list[Read], list[int], ErrorModelSpec], ErrorModelSpec]
Draw = Callable[[np.random.Generator, int], tuple[list[str], list[int]]]
TOLERANCES = {"rate": 0.05, "rate_by_q": 0.10, "q_position_tv": 0.05}
_K = len(error.CATEGORIES)


def example_spec() -> ErrorModelSpec:
    """A small Illumina-like truth (binned Q, reads of 30-40 bases) that exercises both heads."""
    errors = np.r_[0, np.ones(_K - 1)]
    lags = np.zeros((1, 5, 4))
    lags[0, :4] = 2.5 * np.eye(4)  # sticky qualities
    q_context = np.zeros((3, 5, 4))
    q_context[1, 2] = [1.5, 0.5, -0.5, -1.5]  # low Q on G
    window = np.zeros((3, 5, _K))
    window[1, :4] = np.outer([2.0, 1.0, 0.0, -1.0], errors)  # more errors at low Q
    window[2, :4] = np.outer([0.7, 0.3, 0.0, -0.3], errors)  # and before a low-Q base
    e_context = np.zeros((3, 5, _K))
    e_context[0, 2, 1:5] = 1.2  # substitutions after G
    runs = np.zeros((5, _K))
    runs[2:, 5:] = 1.5  # indels in runs of 3+
    return ErrorModelSpec(
        (2, 12, 23, 37),
        {"mode": "reference", "sources": ["example"]},
        (
            Component("QualityMarkov(1)", {"bias": np.array([-1.0, 0.0, 0.5, 1.5]), "lags": lags}),
            Component(
                "Position(3)",
                {
                    "knots": np.linspace(0, np.log(40), 3),
                    "start": np.zeros((3, 4)),
                    "end": np.array([[1.5, 0.5, -0.5, -1.5], [0] * 4, [0] * 4]),  # end-of-read decay
                },
            ),
            Component("Mate", {"weights": np.array([[0, 0, 0, 0.5], [0.5, 0, 0, -0.5]])}),
            Component("Context(1,1)", {"weights": q_context}),
        ),
        (
            Component(
                "QualityWindow(1)",
                {"bias": np.array([0, -4.0, -4.0, -4.0, -4.0, -6.5, -6.5, -6.5, -6.5, -6.0]), "window": window},
            ),
            Component("Context(1,1)", {"weights": e_context}),
            Component("Homopolymer", {"weights": runs}, meta={"flank": [2, 2]}),
            Component("Mate", {"weights": np.outer([0, 0.3], errors)}),
        ),
    )


def _tuples(model: ErrorModelSpec, templates: Sequence[str], reads: Sequence[Read], mates: Sequence[int]) -> CountTable:
    """Head E tuples wide enough for both heads' context and Q windows."""
    e, q = _flank(model.error_head), _flank(model.quality_head)
    m = max(model.error_head[0].args[0], model.quality_head[0].args[0])
    per_event = indel.split(model.error_head)[1] is not None
    return observations(
        zip(templates, reads, mates, strict=True), (max(e[0], q[0]), max(e[1], q[1])), m, per_event=per_event
    )


def cigar_mode(templates: list[str], reads: list[Read], mates: list[int], truth: ErrorModelSpec) -> ErrorModelSpec:
    """Refit both heads (with the truth's tokens) from tuples re-derived from the generator's own CIGARs."""
    return bam.fit(
        _tuples(truth, templates, reads, mates),
        truth.quality_alphabet,
        [c.token for c in truth.error_head],
        [c.token for c in truth.quality_head],
        {"mode": "reference", "sources": ["generator-cigar"]},
        indel_events(zip(templates, reads, mates, strict=True)) if indel.split(truth.error_head)[1] else None,
    )


@dataclass
class Report:
    scalars: dict[str, float] = field(default_factory=dict)
    curves: dict[str, list[float]] = field(default_factory=dict)

    def failures(self) -> list[str]:
        """Phase 2 exit criteria that this report misses."""
        out = []
        if abs(self.scalars["rate_ratio"] - 1) > TOLERANCES["rate"]:
            out.append(f"marginal error rate ratio {self.scalars['rate_ratio']:.3f}")
        by_q = np.array(self.curves["rate_by_q_fit"]) / np.array(self.curves["rate_by_q_true"])
        if np.nanmax(np.abs(by_q - 1)) > TOLERANCES["rate_by_q"]:
            out.append(f"error rate ratio by reported Q {np.round(by_q, 3).tolist()}")
        if self.scalars["q_position_tv_max"] > TOLERANCES["q_position_tv"]:
            out.append(f"per-position Q TV {self.scalars['q_position_tv_max']:.3f}")
        return out


def _rate(key: Array, values: Array, errors: Array, n: Array) -> list[float]:
    return [float(errors[key == v].sum() / n[key == v].sum()) if (key == v).any() else float("nan") for v in values]


def _q_hist(tracks: Sequence[Array], alphabet: Array, top: int) -> Array:
    h = np.zeros((top, len(alphabet)))
    for track in tracks:
        np.add.at(h, (np.arange(top), np.searchsorted(alphabet, track[:top])), 1)
    return h / h.sum(axis=1, keepdims=True)


def _lag1(tracks: Sequence[Array]) -> float:
    x = np.concatenate([t[:-1] for t in tracks])
    y = np.concatenate([t[1:] for t in tracks])
    return float(np.corrcoef(x, y)[0, 1])


def compare(
    truth: ErrorModelSpec,
    fitted: ErrorModelSpec,
    templates: Sequence[str],
    mates: Sequence[int],
    rng: np.random.Generator,
    q_reads: int = 20000,
    substitutions_only: bool = False,
) -> Report:
    """Metrics of `fitted` against `truth` on reads generated from `templates`; Q-track statistics use at least
    `q_reads` sampled tracks per spec. `substitutions_only` compares both heads E conditional on no indel, the
    support of `pe-overlap`."""
    alphabet = np.asarray(truth.quality_alphabet)
    true_reads = generate(truth, templates, mates, rng)
    table = _tuples(truth, templates, true_reads, mates)
    n = np.array(list(table.counts.values()), float)
    p_true, p_fit = (
        error.probabilities(indel.split(s.error_head)[0], truth.quality_alphabet, table) for s in (truth, fitted)
    )
    if substitutions_only:
        p_true, p_fit = (
            np.pad(p[:, :5] / p[:, :5].sum(axis=1, keepdims=True), ((0, 0), (0, _K - 5))) for p in (p_true, p_fit)
        )
    with np.errstate(divide="ignore", invalid="ignore"):
        kl = np.where(p_true > 0, p_true * np.log(p_true / p_fit), 0.0).sum(axis=1)
    e_true, e_fit = n * (1 - p_true[:, 0]), n * (1 - p_fit[:, 0])
    q, pos = (np.array([k[table.fields.index(f)] for k in table.counts]) for f in ("q", "pos_start"))
    positions = np.unique(pos)

    # Q-track statistics compare two samples, so draw enough tracks (tiling the templates) that sampling
    # noise stays well under the TV tolerance.
    reps = -(-q_reads // len(templates))
    tiled, tiled_mates = list(templates) * reps, list(mates) * reps
    q_true, q_fit = (
        quality.sample(s.quality_head, truth.quality_alphabet, tiled, tiled_mates, rng) for s in (truth, fitted)
    )
    top = min(len(t) for t in templates)
    tv = 0.5 * np.abs(_q_hist(q_true, alphabet, top) - _q_hist(q_fit, alphabet, top)).sum(axis=1)
    rate_q = {name: _rate(q, alphabet, e, n) for name, e in (("true", e_true), ("fit", e_fit))}
    return Report(
        scalars={
            "op_tv": float(n @ (0.5 * np.abs(p_true - p_fit).sum(axis=1)) / n.sum()),
            "op_kl": float(n @ kl / n.sum()),
            "rate_true": float(e_true.sum() / n.sum()),
            "rate_fit": float(e_fit.sum() / n.sum()),
            "rate_ratio": float(e_fit.sum() / e_true.sum()),
            "q_position_tv_max": float(tv.max()),
            "q_lag1_true": _lag1(q_true),
            "q_lag1_fit": _lag1(q_fit),
        },
        curves={
            "reported_q": alphabet.tolist(),
            "rate_by_q_true": rate_q["true"],
            "rate_by_q_fit": rate_q["fit"],
            "empirical_q_true": (-10 * np.log10(rate_q["true"])).tolist(),
            "empirical_q_fit": (-10 * np.log10(rate_q["fit"])).tolist(),
            "position": positions.tolist(),
            "rate_by_position_true": _rate(pos, positions, e_true, n),
            "rate_by_position_fit": _rate(pos, positions, e_fit, n),
            "q_position_tv": tv.tolist(),
        },
    )


def recover(
    truth: ErrorModelSpec,
    n_reads: int,
    seed: int = 0,
    mode: Mode = cigar_mode,
    lengths: tuple[int, int] = (30, 41),
    draw: Draw | None = None,
    substitutions_only: bool = False,
) -> tuple[ErrorModelSpec, Report]:
    """Generate `n_reads` from `truth`, fit with `mode`, and compare on `n_reads // 2` held-out reads.

    `draw(rng, n)` gives n templates and their mates (default: independent random reads of `lengths`)."""
    rng = np.random.default_rng(seed)

    def single(rng: np.random.Generator, n: int) -> tuple[list[str], list[int]]:
        templates = ["".join(rng.choice(list("ACGT"), size=rng.integers(*lengths))) for _ in range(n)]
        return templates, [int(m) for m in rng.integers(1, 3, size=n)]

    draw = draw or single
    templates, mates = draw(rng, n_reads)
    fitted = mode(templates, generate(truth, templates, mates, rng), mates, truth)
    held, held_mates = draw(rng, max(n_reads // 2, 2))
    return fitted, compare(truth, fitted, held, held_mates, rng, substitutions_only=substitutions_only)


def _slope(true: Array, fitted: Array) -> float:
    """Least-squares slope of fitted on true `Context` log-odds (error vs match, centred over A, C, G, T): 1 is
    unbiased, below 1 a shrunk effect."""
    x, y = ((w[:, :4, 1:] - w[:, :4, :1]) for w in (true, fitted))
    x, y = (v - v.mean(axis=1, keepdims=True) for v in (x, y))
    return round(float(x.ravel() @ y.ravel() / (x.ravel() @ x.ravel())), 3)


def _op_class(op: str) -> str:
    return "match" if op == "=" else "insertion" if op[0] == "-" else "deletion" if op[-1] == "-" else "substitution"


_RUNS = ("1", "2", "3+")


def indel_profile(records: Sequence[tuple[str, Read, int]], max_length: int = 4) -> dict[str, dict[str, Any]]:
    """Indel events per template base, and their length distribution (lengths above `max_length` pooled), by
    kind and the template base's homopolymer run (1, 2, 3+)."""
    bases = Counter[str]()
    for template, _, _ in records:
        for _, stretch in groupby(template.upper()):
            size = len(list(stretch))
            bases[_RUNS[min(size, 3) - 1]] += size
    lengths: dict[str, Array] = {}
    for (kind, length, run, _), c in indel_events(records).counts.items():
        h = lengths.setdefault(f"{kind}:{_RUNS[min(int(str(run)), 3) - 1]}", np.zeros(max_length))
        h[min(int(str(length)), max_length) - 1] += c
    return {
        key: {"rate": float(h.sum() / bases[key[2:]]), "lengths": (h / h.sum()).tolist()}
        for key, h in sorted(lengths.items())
    }


def indel_components(a: ErrorModelSpec, b: ErrorModelSpec, table: CountTable) -> dict[str, float]:
    """Per-component indel check (plan phase 5): expected deletion (D) and insertion (I) counts under head E of
    `b` over those under `a`, on `table`'s rows, grouped by the centre base's homopolymer run inside the context
    window (`Homopolymer`: "D run 3+") and by the base at each context offset (`Context`: "I -1G"). On random
    templates the other components average out of each group, so a ratio away from 1 is that component's indel
    effect moved; the phase 2 per-Q tolerance (10%) applies."""
    n = np.array(list(table.counts.values()), float)
    expected = {}
    for name, s in (("a", a), ("b", b)):
        p = error.probabilities(indel.split(s.error_head)[0], a.quality_alphabet, table)
        expected[name] = {"D": n * p[:, 9], "I": n * p[:, 5:9].sum(axis=1)}
    f0 = table.meta["flank"][0]
    contexts = [str(k[table.fields.index("context")]) for k in table.counts]
    runs = []
    for c in contexts:
        left = len(c[: f0 + 1]) - len(c[: f0 + 1].rstrip(c[f0]))
        right = len(c[f0:]) - len(c[f0:].lstrip(c[f0]))
        runs.append(_RUNS[min(left + right - 1, 3) - 1])
    groups = {f"run {r}": np.array(runs) == r for r in _RUNS}
    chars = np.array([list(c) for c in contexts])
    for i in range(chars.shape[1]):
        for base in "ACGT":
            groups[f"{i - f0:+d}{base}"] = chars[:, i] == base
    return {
        f"{kind} {g}": round(float(expected["b"][kind][sel].sum() / expected["a"][kind][sel].sum()), 3)
        for kind in ("D", "I")
        for g, sel in groups.items()
        if sel.any()
    }


def _refit_error(truth: ErrorModelSpec, table: CountTable, records: Sequence[tuple[str, Read, int]]) -> ErrorModelSpec:
    """The truth with head E (and any `IndelLength`) refitted with its tokens from `table` and `records`."""
    body, length_head = indel.split(truth.error_head)
    head = tuple(error.fit(table, [c.token for c in body], truth.quality_alphabet))
    if length_head is not None:
        head += (indel.fit(indel_events(records), length_head.token, truth.quality_alphabet),)
    return replace(truth, error_head=head)


def mask_cost(
    truth: ErrorModelSpec,
    alt_freqs: Sequence[float] = (0.1, 0.2, 0.5),
    genome_length: int = 20_000,
    depth: float = 30.0,
    lengths: tuple[int, int] = (30, 41),
    seed: int = 0,
) -> dict[str, Any]:
    """Clonal cost of site masks (plan phase 5): reads from one random genome, so every mismatch is an error and
    every masked site removes true errors. For no mask and each `max_alt_freq`, report what the mask removes (rows,
    errors, op classes, most enriched trinucleotide contexts) and how head E refitted on the kept tuples compares
    with the truth on held-out reads (head Q and any `IndelLength` are kept at the truth).

    ponytail: the contig depth filter is not measured; on clonal reads it keeps or drops whole contigs by depth,
    which isn't the outcome, so it costs data but can't bias head E."""
    rng = np.random.default_rng(seed)
    genome = "".join(rng.choice(list("ACGT"), size=genome_length))
    n = int(depth * genome_length / np.mean(lengths))
    size = rng.integers(*lengths, size=n)
    start, reverse = rng.integers(0, genome_length - size + 1), rng.random(n) < 0.5
    fwd = [genome[s : s + k] for s, k in zip(start, size, strict=True)]
    templates = [_revcomp(t) if r else t for t, r in zip(fwd, reverse, strict=True)]
    mates = [int(m) for m in rng.integers(1, 3, size=n)]
    reads = generate(truth, templates, mates, rng)
    alignments = [
        ("g", int(s), int(s + k), bool(r), t, read, m)
        for s, k, r, t, read, m in zip(start, size, reverse, templates, reads, mates, strict=True)
    ]
    counts = bam.count_alleles(alignments, {"g": genome_length})
    body, length_head = indel.split(truth.error_head)
    held = ["".join(rng.choice(list("ACGT"), size=rng.integers(*lengths))) for _ in range(n // 2)]
    held_mates = [int(m) for m in rng.integers(1, 3, size=len(held))]

    base = _tuples(truth, templates, reads, mates)
    oi, ci, f0 = base.fields.index("op"), base.fields.index("context"), base.meta["flank"][0]

    def errors(c: Counter[Key], by: Callable[[Key], str]) -> Counter[str]:
        out: Counter[str] = Counter()
        for k, v in c.items():
            if k[oi] != "=":
                out[by(k)] += v
        return out

    def trinucleotide(k: Key) -> str:
        return str(k[ci])[f0 - 1 : f0 + 2]

    all_errors = errors(base.counts, trinucleotide)
    settings = []
    for freq in (None, *alt_freqs):
        masked = bam.site_masks(counts, lambda _: genome, freq)[0]
        kept = list(zip(*bam.apply_masks(alignments, masked), strict=True))
        table = _tuples(truth, list(kept[0]), list(kept[1]), list(kept[2]))
        removed = base.counts - table.counts
        gone = errors(removed, trinucleotide)
        enriched = sorted(
            ((c, (gone[c] / gone.total()) / (all_errors[c] / all_errors.total())) for c in gone if gone[c] >= 10),
            key=lambda x: -x[1],
        )
        head = error.fit(table, [c.token for c in body], truth.quality_alphabet)
        true_ctx, fit_ctx = (next((c.params["weights"] for c in h if c.name == "Context"), None) for h in (body, head))
        fitted = replace(truth, error_head=(*head, *([length_head] if length_head else [])))
        report = compare(truth, fitted, held, held_mates, rng, q_reads=len(held))
        by_q = np.array(report.curves["rate_by_q_fit"]) / np.array(report.curves["rate_by_q_true"])
        settings.append(
            {
                "max_alt_freq": freq,
                "masked_sites": int(masked["g"].sum()),
                "removed_rows": removed.total(),
                "removed_errors": gone.total(),
                "removed_error_fraction": gone.total() / all_errors.total(),
                "removed_row_error_rate": gone.total() / max(1, removed.total()),
                "row_error_rate": all_errors.total() / base.counts.total(),
                "removed_errors_by_op": dict(errors(removed, lambda k: _op_class(str(k[oi])))),
                "errors_by_op": dict(errors(base.counts, lambda k: _op_class(str(k[oi])))),
                "enriched_contexts": [(c, round(r, 2)) for c, r in enriched[:5]],
                "rate_ratio": report.scalars["rate_ratio"],
                "op_tv": report.scalars["op_tv"],
                "rate_by_q_ratio": np.round(by_q, 3).tolist(),
                "context_slope": None if true_ctx is None or fit_ctx is None else _slope(true_ctx, fit_ctx),
                "failures": [f for f in report.failures() if not f.startswith("per-position Q")],
            }
        )
    return {"reads": n, "genome_length": genome_length, "depth": depth, "seed": seed, "settings": settings}


ALIGNER_SCORES = {"minibwa": (2, 8, 12, 2), "minimap2": (2, 4, 4, 2)}  # match, mismatch, gap open, extend
ALIGNER_READS = {"minibwa": (100, 151), "minimap2": (1000, 2001)}  # default read lengths: short, long


def run_aligner(aligner: str, reference: Path, reads: Path, sam: Path, preset: str = "map-ont") -> None:
    """Align single-end FASTQ `reads` to `reference` as SAM: minibwa for short reads, minimap2 (`-x preset`) for
    long reads."""
    if aligner == "minibwa":
        subprocess.run(["minibwa", "index", str(reference)], check=True, capture_output=True)
        cmd = ["minibwa", "map", str(reference), str(reads)]
    elif aligner == "minimap2":
        cmd = ["minimap2", "-a", "-x", preset, str(reference), str(reads)]
    else:
        raise ValueError(f"unknown aligner {aligner!r}; use minibwa or minimap2")
    with sam.open("w") as out:
        subprocess.run(cmd, check=True, stdout=out, stderr=subprocess.PIPE)


def aligner_bias(
    truth: ErrorModelSpec,
    aligner: str,
    workdir: Path,
    n_reads: int = 400,
    lengths: tuple[int, int] | None = None,
    genome_length: int = 20_000,
    error_rate_scale: float = 1.0,
    preset: str = "map-ont",
    seed: int = 0,
    min_mapq: int = 20,
    unclip: bool = False,
) -> dict[str, Any]:
    """Aligner bias check (plan phase 5): align generated single-end reads, whose true CIGARs are known, back to
    their random genome and report how the aligner changes the evidence. With `unclip`, the BAM source realigns
    soft-clipped reads end to end under the aligner's scores (`sources.bam`), the correction for clipping.

    The truth's error rate is scaled by `error_rate_scale` (non-match logits shifted by its log, exactly what
    `generate(error_rate_scale=)` does) and the scaled spec is the truth throughout. Reported, true vs aligned:
    mapped fraction; op-class rates per head E row; per reference site, the fraction of true substitution,
    deletion and insertion counts the alignments place at the same site; mean indel length per kind; and head E
    (with any `IndelLength`) refitted from the aligned tuples against the truth on held-out reads (head Q kept).

    Generated CIGARs can hold edits no alignment recovers (a deletion and an insertion of one base in a
    homopolymer run cancel), so the metrics are also reported against the observable truth: each whole true read
    `realign`ed under the aligner's own scores (`ALIGNER_SCORES`, first affine gap of each) to the genome around
    its true span, with free template ends, indels left-aligned (`*_observable`, plus indel rates and lengths by
    run). The true span's ends aren't observable either: an indel next to a read end can score the same or worse
    than a shifted end. That isolates the aligner's heuristics
    (seeding, bands, clipping); `edits_hidden` and `observable_rate_ratio` size what even the optimal alignment
    doesn't show."""
    lengths = lengths or ALIGNER_READS[aligner]
    head0 = truth.error_head[0]
    shift = np.r_[0.0, np.full(_K - 1, np.log(error_rate_scale))]
    scaled = (replace(head0, params={**head0.params, "bias": head0.params["bias"] + shift}), *truth.error_head[1:])
    truth = replace(truth, error_head=scaled)

    rng = np.random.default_rng(seed)
    genome = "".join(rng.choice(list("ACGT"), size=genome_length))
    size = rng.integers(*lengths, size=n_reads)
    start, reverse = rng.integers(0, genome_length - size + 1), rng.random(n_reads) < 0.5
    fwd = [genome[s : s + k] for s, k in zip(start, size, strict=True)]
    templates = [_revcomp(t) if r else t for t, r in zip(fwd, reverse, strict=True)]
    mates = [1] * n_reads
    reads = [
        replace(r, strand="-" if rev else "+")
        for r, rev in zip(generate(truth, templates, mates, rng), reverse, strict=True)
    ]
    reference, fastq, sam = workdir / "ref.fa", workdir / "reads.fq", workdir / f"{aligner}.sam"
    reference.write_text(f">g\n{genome}\n")
    fastq.write_text("".join(f"@r{i}\n{r.sequence}\n+\n{r.quality}\n" for i, r in enumerate(reads)))
    run_aligner(aligner, reference, fastq, sam, preset)

    scores = ALIGNER_SCORES[aligner]
    aligned = list(bam.records(sam, reference, min_mapq, unclip=scores if unclip else None))
    a_templates, a_reads, a_mates = (list(x) for x in zip(*aligned, strict=True)) if aligned else ([], [], [])
    margin = bam._UNCLIP_MARGIN
    observed = []  # (forward start, forward end, template, read)
    for s, k, rev, r in zip(start, size, reverse, reads, strict=True):
        lo, hi = max(0, int(s) - margin), min(genome_length, int(s + k) + margin)
        window = _revcomp(genome[lo:hi]) if rev else genome[lo:hi]
        best, s0, s1 = realign(window, r, scores, free_template_ends=True)
        span = (hi - s1, hi - s0) if rev else (lo + s0, lo + s1)
        observed.append((*span, window[s0:s1], best))
    o_templates, observable = [o[2] for o in observed], [o[3] for o in observed]
    true_table, aligned_table = _tuples(truth, templates, reads, mates), _tuples(truth, a_templates, a_reads, a_mates)
    observable_table = _tuples(truth, o_templates, observable, mates)
    true_records = list(zip(templates, reads, mates, strict=True))
    observable_records = list(zip(o_templates, observable, mates, strict=True))

    def op_rates(table: CountTable) -> dict[str, float]:
        oi, c = table.fields.index("op"), Counter[str]()
        for k, v in table.counts.items():
            c[_op_class(str(k[oi]))] += v
        return {k: v / c.total() for k, v in sorted(c.items())}

    def mean_lengths(records: Sequence[tuple[str, Read, int]]) -> dict[str, float]:
        n, total = Counter[str](), Counter[str]()
        for (kind, length, *_), v in indel_events(records).counts.items():
            n[str(kind)] += v
            total[str(kind)] += v * int(str(length))
        return {k: total[k] / n[k] for k in sorted(n)}

    placed = [
        ("g", int(s), int(s + k), bool(rev), t, r, 1)
        for s, k, rev, t, r in zip(start, size, reverse, templates, reads, strict=True)
    ]
    true_counts = bam.count_alleles(placed, {"g": genome_length})["g"]
    observable_counts = bam.count_alleles(
        [("g", s, e, bool(rev), t, o, 1) for (s, e, t, o), rev in zip(observed, reverse, strict=True)],
        {"g": genome_length},
    )["g"]
    aligned_counts = bam.pileup(sam, reference, min_mapq, scores if unclip else None).get(
        "g", np.zeros_like(true_counts)
    )
    ref = np.array(["ACGT".index(b) for b in genome] + [0])

    def columns(c: Array) -> dict[str, Array]:
        subs = c[:, :4].copy()
        subs[np.arange(len(ref)), ref] = 0
        return {"substitution": subs, "deletion": c[:, 4], "insertion": c[:, 5]}

    true_cols, aligned_cols, observable_cols = (columns(c) for c in (true_counts, aligned_counts, observable_counts))
    rates_true, rates_aligned, rates_observable = (op_rates(t) for t in (true_table, aligned_table, observable_table))
    profiles = {"true": indel_profile(true_records), "observable": indel_profile(observable_records)}
    profiles["aligned"] = indel_profile(aligned)

    fitted = _refit_error(truth, aligned_table, aligned)
    observable_fit = _refit_error(truth, observable_table, observable_records)
    held = ["".join(rng.choice(list("ACGT"), size=rng.integers(*lengths))) for _ in range(max(n_reads // 2, 2))]
    held_mates = [1] * len(held)
    report = compare(truth, fitted, held, held_mates, rng, q_reads=len(held))
    against_observable = compare(observable_fit, fitted, held, held_mates, rng, q_reads=len(held))
    identified = compare(truth, observable_fit, held, held_mates, rng, q_reads=len(held))
    held_table = _tuples(truth, held, generate(truth, held, held_mates, rng), held_mates)
    components = indel_components(truth, fitted, held_table)
    components_observable = indel_components(observable_fit, fitted, held_table)

    def by_q(r: Report) -> list[float]:
        ratio = np.array(r.curves["rate_by_q_fit"]) / np.array(r.curves["rate_by_q_true"])
        return [round(float(x), 3) for x in ratio]

    def error_failures(r: Report) -> list[str]:
        return [f for f in r.failures() if not f.startswith("per-position Q")]

    def length_tv(a: dict[str, Any], b: dict[str, Any]) -> float:
        return round(0.5 * float(np.abs(np.array(a["lengths"]) - np.array(b["lengths"])).sum()), 3)

    return {
        "aligner": aligner,
        "preset": preset if aligner == "minimap2" else None,
        "reads": n_reads,
        "lengths": list(lengths),
        "error_rate_scale": error_rate_scale,
        "unclip": unclip,
        "mapped_fraction": len(aligned) / n_reads,
        "op_rates_true": rates_true,
        "op_rates_aligned": rates_aligned,
        "op_rate_ratio": {k: rates_aligned.get(k, 0.0) / v for k, v in rates_true.items()},
        "site_agreement": {
            k: float(np.minimum(v, aligned_cols[k]).sum() / max(1, v.sum())) for k, v in true_cols.items()
        },
        "mean_indel_length_true": mean_lengths(list(zip(templates, reads, mates, strict=True))),
        "mean_indel_length_aligned": mean_lengths(aligned),
        "rate_ratio": report.scalars["rate_ratio"],
        "op_tv": report.scalars["op_tv"],
        "rate_by_q_ratio": by_q(report),
        "failures": error_failures(report),
        "edits_hidden": 1
        - sum(_edits(t, r) for t, r, _ in observable_records) / sum(_edits(t, r) for t, r, _ in true_records),
        "observable_rate_ratio": identified.scalars["rate_ratio"],
        "op_rates_observable": rates_observable,
        "op_rate_ratio_observable": {k: rates_aligned.get(k, 0.0) / v for k, v in rates_observable.items()},
        "site_agreement_observable": {
            k: float(np.minimum(v, aligned_cols[k]).sum() / max(1, v.sum())) for k, v in observable_cols.items()
        },
        "indel_by_run": profiles,
        "indel_rate_ratio_observable": {
            k: round(profiles["aligned"][k]["rate"] / v["rate"], 3) if k in profiles["aligned"] else 0.0
            for k, v in profiles["observable"].items()
        },
        "indel_length_tv_observable": {
            k: length_tv(v, profiles["aligned"][k])
            for k, v in profiles["observable"].items()
            if k in profiles["aligned"]
        },
        "rate_ratio_observable": against_observable.scalars["rate_ratio"],
        "op_tv_observable": against_observable.scalars["op_tv"],
        "rate_by_q_ratio_observable": by_q(against_observable),
        "failures_observable": error_failures(against_observable),
        "indel_components": components,
        "indel_components_observable": components_observable,
        "indel_component_failures_observable": {
            k: v for k, v in components_observable.items() if abs(v - 1) > TOLERANCES["rate_by_q"]
        },
    }


def paired_draw(read_length: int, insert_mean: float, insert_sd: float, genome_length: int = 100_000) -> Draw:
    """A `draw` of interleaved mate 1, mate 2 templates from `generate.fragments` on a random genome."""

    def draw(rng: np.random.Generator, n: int) -> tuple[list[str], list[int]]:
        genome = "".join(rng.choice(list("ACGT"), size=genome_length))
        pairs = fragments([("g", genome)], insert_sizes(insert_mean, insert_sd), n // 2, read_length, rng)
        return [t for _, r1, r2 in pairs for t in (r1, r2)], [1, 2] * (n // 2)

    return draw


def main(argv: Sequence[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        prog="python -m sequencing_error_model.recovery", description="Recovery harness: generate, refit, compare."
    )
    p.add_argument("--spec", type=Path, help="truth spec directory (default: the built-in example spec)")
    p.add_argument("--reads", type=int, default=3000)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--output", type=Path, help="write the full report as JSON")
    p.add_argument("--mask-cost", action="store_true", help="report the clonal cost of site masks instead")
    p.add_argument("--genome-length", type=int, default=20_000, help="with --mask-cost")
    p.add_argument("--depth", type=float, default=30.0, help="with --mask-cost")
    p.add_argument("--aligner", choices=sorted(ALIGNER_READS), help="report aligner bias instead (uses --reads)")
    p.add_argument("--error-rate-scale", type=float, default=1.0, help="with --aligner")
    p.add_argument("--preset", default="map-ont", help="minimap2 preset, with --aligner minimap2")
    p.add_argument("--unclip", action="store_true", help="with --aligner: realign soft-clipped reads end to end")
    args = p.parse_args(argv)
    if args.mask_cost or args.aligner:
        truth = spec_io.load(args.spec) if args.spec else example_spec()
        doc: dict[str, Any]
        if args.aligner:
            with tempfile.TemporaryDirectory() as tmp:
                doc = aligner_bias(
                    truth,
                    args.aligner,
                    Path(tmp),
                    args.reads,
                    genome_length=args.genome_length,
                    error_rate_scale=args.error_rate_scale,
                    preset=args.preset,
                    seed=args.seed,
                    unclip=args.unclip,
                )
        else:
            doc = mask_cost(truth, genome_length=args.genome_length, depth=args.depth, seed=args.seed)
        text = json.dumps(doc, indent=2) + "\n"
        if args.output:
            args.output.write_text(text)
        print(text, end="")
        return 0
    _, report = recover(spec_io.load(args.spec) if args.spec else example_spec(), args.reads, args.seed)
    doc = {"reads": args.reads, "seed": args.seed, "failures": report.failures(), **vars(report)}
    if args.output:
        args.output.write_text(json.dumps(doc, indent=2) + "\n")
    print(json.dumps({"failures": doc["failures"], **report.scalars}, indent=2))
    return 1 if doc["failures"] else 0


if __name__ == "__main__":
    sys.exit(main())
